export const translations = {
  en: {
    title: "VoiceShield",
    tagline: "Detect AI Voice Impersonation Before It Becomes a Threat",
    taglineSub: "Protect your systems, communications, and assets with real-time deepfake audio analysis and explainable security intelligence.",
    landingCta1: "Start Analysis",
    landingCta2: "Live Detection",
    landingCta3: "View Dashboard",
    navHome: "Home",
    navDashboard: "Dashboard",
    navScan: "Analyze Audio",
    navLive: "Live Detection",
    navVerify: "Identity Verify",
    navModels: "Model Hub",
    navArchitecture: "Architecture",
    demoModeActive: "DEMO MODE ACTIVE — Outputs are not validated model predictions",
    demoModeBtn: "Demo Mode",
    language: "Language",
    totals: "Total Audited Scans",
    highRisk: "High Risk Alerts",
    medRisk: "Medium Risk Scans",
    lowRisk: "Low Risk Scans",
    avgProb: "Avg Synthetic Prob",
    avgProc: "Avg Scan Latency",
    historyTable: "Incident Log History",
    historyDesc: "Detailed list of audio scans, risk levels, and explainable evidence.",
    incidentId: "Incident ID",
    timestamp: "Timestamp",
    fileName: "File Name",
    outcome: "Scan Outcome",
    syntheticProb: "Synthetic Probability",
    realProb: "Real Probability",
    confidence: "Confidence",
    riskLevel: "Risk Level",
    procTime: "Processing Time",
    actions: "Actions",
    viewReport: "View Report",
    downloadReport: "Download PDF",
    deleteScan: "Purge Scan",
    modelPipeline: "Model Pipeline Info",
    modelVersion: "Model Version",
    explainableAI: "Explainable AI Narrative",
    securityChecklist: "Incident Action Checklist",
    assistantTitle: "VoiceShield AI Assistant",
    assistantPlaceholder: "Ask about scan results, deepfake risk details...",
    registerVoice: "Register Reference Voice",
    registerDesc: "Record or upload a trusted audio sample to establish an acoustic identity print.",
    compareVoice: "Verify Incoming Voice",
    compareDesc: "Compare an incoming audio file against a registered reference print to evaluate similarity and spoof risk.",
    identityMatch: "Voice Identity Match",
    deepfakeRisk: "Synthetic Voice Risk",
    matchScore: "Identity Similarity",
    authenticityWarning: "WARNING: Identity verification only measures vocal similarity. An AI-cloned voice can impersonate a target's voice print. Always cross-check the Synthetic Voice Risk rating.",
    howItWorks: "Defense-In-Depth Security Analysis",
    step1: "Audio Capture",
    step1Desc: "Upload WAV/MP3 files or record raw live microphone streams securely.",
    step2: "Feature Extraction",
    step2Desc: "Extract 13-dimensional MFCCs (Mel-frequency cepstral coefficients) of vocal tracks.",
    step3: "PyTorch Inference",
    step3Desc: "Run the feature matrix through a deep neural classifier to score spoofing probability.",
    step4: "Explainable AI (Gemini)",
    step4Desc: "Feed numerical logits to Gemini to generate standard plain-language cybersecurity evidence reports.",
    privacyNotice: "Privacy & Compliance Notice: VoiceShield adheres to SOC2 regulations. Scanned audio files are analyzed temporarily in-memory and immediately purged upon analysis. We do not store raw voice samples.",
    howItWorksTitle: "How It Works",
    modelStatus: "Model Pipeline & Analytics Dashboard",
    modelName: "Model Name",
    status: "Status",
    auc: "Area Under ROC (AUC)",
    eer: "Equal Error Rate (EER)",
    dataset: "Training Dataset",
    lastUpdated: "Last Weights Update",
    modelDesc: "Overview of neural networks and active model architectures running on this node."
  },
  hi: {
    title: "वॉयसशील्ड",
    tagline: "खतरे से पहले एआई वॉयस क्लोनिंग का पता लगाएं",
    taglineSub: "रीयल-टाइम डीपफेक ऑडियो विश्लेषण और स्पष्टीकरण योग्य सुरक्षा खुफिया जानकारी के साथ अपने सिस्टम और संचार की रक्षा करें।",
    landingCta1: "विश्लेषण शुरू करें",
    landingCta2: "लाइव डिटेक्शन",
    landingCta3: "डैशबोर्ड देखें",
    navHome: "मुख्य",
    navDashboard: "डैशबोर्ड",
    navScan: "ऑडियो विश्लेषण",
    navLive: "लाइव डिटेक्शन",
    navVerify: "पहचान सत्यापन",
    navModels: "मॉडल हब",
    navArchitecture: "संरचना",
    demoModeActive: "डेमो मोड सक्रिय — परिणाम मान्य मॉडल भविष्यवाणियां नहीं हैं",
    demoModeBtn: "डेमो मोड",
    language: "भाषा",
    totals: "कुल परीक्षित स्कैन",
    highRisk: "उच्च जोखिम अलर्ट",
    medRisk: "मध्यम जोखिम स्कैन",
    lowRisk: "कम जोखिम स्कैन",
    avgProb: "औसत कृत्रिम प्रोब",
    avgProc: "औसत विश्लेषण समय",
    historyTable: "घटना लॉग इतिहास",
    historyDesc: "ऑडियो स्कैन, जोखिम स्तर और साक्ष्य की विस्तृत सूची।",
    incidentId: "घटना आईडी",
    timestamp: "समय",
    fileName: "फ़ाइल का नाम",
    outcome: "स्कैन परिणाम",
    syntheticProb: "कृत्रिम संभावना",
    realProb: "वास्तविक संभावना",
    confidence: "आत्मविश्वास",
    riskLevel: "जोखिम स्तर",
    procTime: "प्रसंस्करण समय",
    actions: "कार्रवाई",
    viewReport: "रिपोर्ट देखें",
    downloadReport: "पीडीएफ डाउनलोड",
    deleteScan: "स्कैन हटाएं",
    modelPipeline: "मॉडल पाइपलाइन जानकारी",
    modelVersion: "मॉडल संस्करण",
    explainableAI: "एआई स्पष्टीकरण",
    securityChecklist: "सुरक्षा चेकलिस्ट",
    assistantTitle: "वॉयसशील्ड एआई सहायक",
    assistantPlaceholder: "स्कैन परिणाम, डीपफेक जोखिम के बारे में पूछें...",
    registerVoice: "संदर्भ आवाज दर्ज करें",
    registerDesc: "ध्वनिक पहचान स्थापित करने के लिए एक विश्वसनीय ऑडियो नमूना रिकॉर्ड या अपलोड करें।",
    compareVoice: "आने वाली आवाज सत्यापित करें",
    compareDesc: "समानता और क्लोनिंग जोखिम का मूल्यांकन करने के लिए एक पंजीकृत संदर्भ के साथ तुलना करें।",
    identityMatch: "आवाज पहचान मिलान",
    deepfakeRisk: "कृत्रिम आवाज जोखिम",
    matchScore: "समानता स्कोर",
    authenticityWarning: "चेतावनी: आवाज मिलान केवल समानता मापता है। एक एआई-क्लोन आवाज किसी की पहचान की नकल कर सकती है। हमेशा कृत्रिम आवाज जोखिम रेटिंग की जांच करें।",
    howItWorks: "गहन सुरक्षा विश्लेषण प्रक्रिया",
    step1: "ऑडियो कैप्चर",
    step1Desc: "WAV/MP3 फ़ाइलें अपलोड करें या सीधे माइक्रोफ़ोन रिकॉर्डिंग करें।",
    step2: "विशेषता निष्कर्षण",
    step2Desc: "आवाज से 13-आयामी एमएफसीसी (MFCC) सुविधाओं को निकालें।",
    step3: "पायटॉर्च अनुमान",
    step3Desc: "डीपफेक क्लोनिंग संभावना का आकलन करने के लिए एक तंत्रिका नेटवर्क में चलाएं।",
    step4: "एआई स्पष्टीकरण (जेमिनी)",
    step4Desc: "जेमिनी की मदद से स्पष्ट भाषा में सुरक्षा रिपोर्ट तैयार करें।",
    privacyNotice: "गोपनीयता सूचना: वॉयसशील्ड SOC2 नियमों का पालन करता है। ऑडियो फाइलें अस्थायी रूप से इन-मेमोरी में संसाधित होती हैं और तुरंत हटा दी जाती हैं।",
    howItWorksTitle: "यह कैसे काम करता है",
    modelStatus: "मॉडल स्थिति और विश्लेषण",
    modelName: "मॉडल नाम",
    status: "स्थिति",
    auc: "AUC मेट्रिक",
    eer: "EER दर",
    dataset: "प्रशिक्षण डेटासेट",
    lastUpdated: "अंतिम अद्यतन",
    modelDesc: "सक्रिय तंत्रिका नेटवर्क और इस नोड पर चल रहे मॉडल वास्तुकला का अवलोकन।"
  },
  kn: {
    title: "ವಾಯ್ಸ್‌ಶೀಲ್ಡ್",
    tagline: "ಕೃತಕ ಧ್ವನಿ ವಂಚನೆಯನ್ನು ಮೊದಲೇ ಪತ್ತೆಹಚ್ಚಿ",
    taglineSub: "ನೈಜ-ಸಮಯದ ಡೀಪ್‌ಫೇಕ್ ಆಡಿಯೊ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಭದ್ರತಾ ಬುದ್ಧಿಮತ್ತೆಯೊಂದಿಗೆ ನಿಮ್ಮ ವ್ಯವಸ್ಥೆಗಳು ಮತ್ತು ಸಂವಹನಗಳನ್ನು ರಕ್ಷಿಸಿ.",
    landingCta1: "ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಿ",
    landingCta2: "ಲೈವ್ ಡಿಟೆಕ್ಷನ್",
    landingCta3: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವೀಕ್ಷಿಸಿ",
    navHome: "ಮುಖಪುಟ",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navScan: "ಆಡಿಯೊ ವಿಶ್ಲೇಷಣೆ",
    navLive: "ಲೈವ್ ಡಿಟೆಕ್ಷನ್",
    navVerify: "ಗುರುತು ಪರಿಶೀಲನೆ",
    navModels: "ಮಾದರಿ ಹಬ್",
    navArchitecture: "ರಚನೆ",
    demoModeActive: "ಡೆಮೊ ಮೋಡ್ ಸಕ್ರಿಯವಾಗಿದೆ — ಫಲಿತಾಂಶಗಳು ದೃಢೀಕರಿಸಲ್ಪಟ್ಟಿಲ್ಲ",
    demoModeBtn: "ಡೆಮೊ ಮೋಡ್",
    language: "ಭಾಷೆ",
    totals: "ಒಟ್ಟು ಆಡಿಟ್ ಮಾಡಿದ ಸ್ಕ್ಯಾನ್‌ಗಳು",
    highRisk: "ಹೆಚ್ಚಿನ ಅಪಾಯದ ಅಲರ್ಟ್‌ಗಳು",
    medRisk: "ಮಧ್ಯಮ ಅಪಾಯದ ಸ್ಕ್ಯಾನ್‌ಗಳು",
    lowRisk: "ಕಡಿಮೆ ಅಪಾಯದ ಸ್ಕ್ಯಾನ್‌ಗಳು",
    avgProb: "ಸರಾಸರಿ ಕೃತಕ ಸಂಭವನೀಯತೆ",
    avgProc: "ಸರಾಸರಿ ವಿಶ್ಲೇಷಣಾ ಸಮಯ",
    historyTable: "ಘಟನೆ ಲಾಗ್ ಇತಿಹಾಸ",
    historyDesc: "ಆಡಿಯೊ ಸ್ಕ್ಯಾನ್‌ಗಳು, ಅಪಾಯದ ಮಟ್ಟಗಳು ಮತ್ತು ಸಾಕ್ಷ್ಯಗಳ ವಿವರವಾದ ಪಟ್ಟಿ.",
    incidentId: "ಘಟನೆ ಐಡಿ",
    timestamp: "ಸಮಯ",
    fileName: "ಫೈಲ್ ಹೆಸರು",
    outcome: "ಸ್ಕ್ಯಾನ್ ಫಲಿತಾಂಶ",
    syntheticProb: "ಕೃತಕ ಧ್ವನಿ ಸಂಭವನೀಯತೆ",
    realProb: "ನೈಜ ಧ್ವನಿ ಸಂಭವನೀಯತೆ",
    confidence: "ವಿಶ್ವಾಸಾರ್ಹತೆ",
    riskLevel: "ಅಪಾಯದ ಮಟ್ಟ",
    procTime: "ಸಂಸ್ಕರಣಾ ಸಮಯ",
    actions: "ಕ್ರಮಗಳು",
    viewReport: "ವರದಿ ವೀಕ್ಷಿಸಿ",
    downloadReport: "ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್",
    deleteScan: "ಸ್ಕ್ಯಾನ್ ಅಳಿಸಿ",
    modelPipeline: "ಮಾದರಿ ಪೈಪ್‌ಲೈನ್ ಮಾಹಿತಿ",
    modelVersion: "ಮಾದರಿ ಆವೃತ್ತಿ",
    explainableAI: "ಎಐ ವಿವರಣೆ",
    securityChecklist: "ಸುರಕ್ಷತಾ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ",
    assistantTitle: "ವಾಯ್ಸ್‌ಶೀಲ್ಡ್ ಎಐ ಸಹಾಯಕ",
    assistantPlaceholder: "ಸ್ಕ್ಯಾನ್ ಫಲಿತಾಂಶಗಳು ಅಥವಾ ಡೀಪ್‌ಫೇಕ್ ಅಪಾಯಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    registerVoice: "ಉಲ್ಲೇಖ ಧ್ವನಿ ನೋಂದಾಯಿಸಿ",
    registerDesc: "ಧ್ವನಿ ಗುರುತನ್ನು ಸ್ಥಾಪಿಸಲು ವಿಶ್ವಾಸಾರ್ಹ ಆಡಿಯೊ ಮಾದರಿಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    compareVoice: "ಬರುವ ಧ್ವನಿ ಪರಿಶೀಲಿಸಿ",
    compareDesc: "ಸಮಾನತೆ ಮತ್ತು ಕೃತಕ ಧ್ವನಿಯ ಅಪಾಯವನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲು ನೋಂದಾಯಿತ ಉಲ್ಲೇಖದೊಂದಿಗೆ ಹೋಲಿಕೆ ಮಾಡಿ.",
    identityMatch: "ಧ್ವನಿ ಗುರುತು ಹೊಂದಾಣಿಕೆ",
    deepfakeRisk: "ಕೃತಕ ಧ್ವನಿ ಅಪಾಯ",
    matchScore: "ಧ್ವನಿ ಹೋಲಿಕೆ ಸ್ಕೋರ್",
    authenticityWarning: "ಎಚ್ಚರಿಕೆ: ಗುರುತು ಪರಿಶೀಲನೆಯು ಕೇವಲ ಧ್ವನಿಯ ಹೋಲಿಕೆಯನ್ನು ಅಳೆಯುತ್ತದೆ. ಎಐ-ಕ್ಲೋನ್ಡ್ ಧ್ವನಿಯು ಗುರಿಯ ಧ್ವನಿಯನ್ನು ಅನುಕರಿಸಬಲ್ಲದು. ಯಾವಾಗಲೂ ಕೃತಕ ಧ್ವನಿ ಅಪಾಯವನ್ನು ಪರೀಕ್ಷಿಸಿ.",
    howItWorks: "ವಾಯ್ಸ್‌ಶೀಲ್ಡ್ ಭದ್ರತಾ ವಿಶ್ಲೇಷಣೆ ಪ್ರಕ್ರಿಯೆ",
    step1: "ಆಡಿಯೋ ಸೆರೆಹಿಡಿಯುವಿಕೆ",
    step1Desc: "WAV/MP3 ಫೈಲ್‌ಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಮೈಕ್ರೊಫೋನ್ ರೆಕಾರ್ಡಿಂಗ್ ಬಳಸಿ.",
    step2: "ವೈಶಿಷ್ಟ್ಯ ಹೊರತೆಗೆಯುವಿಕೆ",
    step2Desc: "ಧ್ವನಿಯಿಂದ 13-ಆಯಾಮದ ಎಂಎಫ್‌ಸಿಸಿ (MFCC) ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಹೊರತೆಗೆಯಿರಿ.",
    step3: "ಪೈಟಾರ್ಚ್ ತೀರ್ಮಾನ",
    step3Desc: "ಡೀಪ್‌ಫೇಕ್ ಸಂಭವನೀಯತೆಯನ್ನು ಸ್ಕೋರ್ ಮಾಡಲು ತೀರ್ಮಾನ ತಂತ್ರಜ್ಞಾನಕ್ಕೆ ಕಳುಹಿಸಿ.",
    step4: "ಎಐ ವಿವರಣೆ (ಜೆಮಿನಿ)",
    step4Desc: "ಜೆಮಿನಿ ಬಳಸಿ ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಭದ್ರತಾ ಸಾಕ್ಷ್ಯ ವರದಿಗಳನ್ನು ರಚಿಸಿ.",
    privacyNotice: "ಗೌಪ್ಯತೆ ಸೂಚನೆ: ವಾಯ್ಸ್‌ಶೀಲ್ಡ್ SOC2 ನಿಯಮಗಳನ್ನು ಅನುಸರಿಸುತ್ತದೆ. ಆಡಿಯೊ ಫೈಲ್‌ಗಳನ್ನು ತಾತ್ಕಾಲಿಕವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಿ ತಕ್ಷಣವೇ ಅಳಿಸಲಾಗುತ್ತದೆ.",
    howItWorksTitle: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    modelStatus: "ಮಾದರಿ ಸ್ಥಿತಿ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ",
    modelName: "ಮಾದರಿ ಹೆಸರು",
    status: "ಸ್ಥಿತಿ",
    auc: "AUC ಮೆಟ್ರಿಕ್",
    eer: "EER ಪ್ರಮಾಣ",
    dataset: "ತರಬೇತಿ ಡೇಟಾಸೆಟ್",
    lastUpdated: "ಕೊನೆಯ ಅಪ್ಡೇಟ್",
    modelDesc: "ಸಕ್ರಿಯ ನರಮಂಡಲ ಜಾಲಗಳು ಮತ್ತು ಈ ನೋಡ್‌ನಲ್ಲಿ ಚಾಲನೆಯಲ್ಲಿರುವ ಮಾದರಿ ರಚನೆಯ ಅವಲೋಕನ."
  }
};
