export const translations = {
  en: {
    title: "VoiceShield",
    tagline: "Detect AI Voice Impersonation Before It Becomes a Threat",
    taglineSub: "Protect your systems, communications, and assets with real-time deepfake audio analysis, YOLO video recognition, and explainable security intelligence.",
    landingCta1: "Start Audio Scan",
    landingCta2: "YOLO Video Scan",
    landingCta3: "View Dashboard",
    navHome: "Home",
    navDashboard: "Dashboard",
    navScan: "Analyze Audio",
    navYolo: "YOLO Video AI",
    navLive: "Live Audio",
    navVerify: "Identity Verify",
    navModels: "Model Hub",
    navArchitecture: "Architecture",
    language: "Language",
    totals: "Total Audited Scans",
    highRisk: "High Risk Alerts",
    medRisk: "Medium Risk Scans",
    lowRisk: "Low Risk Scans",
    avgProb: "Avg Synthetic Prob",
    avgProc: "Avg Scan Latency",
    historyTable: "Incident Log History",
    historyDesc: "Detailed list of audio & video scans, risk levels, and explainable evidence.",
    incidentId: "Incident ID",
    timestamp: "Timestamp",
    fileName: "File Name",
    outcome: "Scan Outcome",
    syntheticProb: "Synthetic Probability",
    realProb: "Real Probability",
    confidence: "Confidence",
    riskLevel: "Risk Level",
    procTime: "Processing Time",
    actions: "Actions",
    viewReport: "View Report",
    downloadReport: "Download PDF",
    deleteScan: "Purge Scan",
    modelPipeline: "Model Pipeline Info",
    modelVersion: "Model Version",
    explainableAI: "Explainable AI Narrative",
    securityChecklist: "Incident Action Checklist",
    assistantTitle: "VoiceShield AI Assistant",
    assistantPlaceholder: "Ask about scan results, deepfake risk details...",
    registerVoice: "Register Reference Voice",
    registerDesc: "Record or upload a trusted audio sample to establish an acoustic identity print.",
    compareVoice: "Verify Incoming Voice",
    compareDesc: "Compare an incoming audio file against a registered reference print to evaluate similarity and spoof risk.",
    identityMatch: "Voice Identity Match",
    deepfakeRisk: "Synthetic Voice Risk",
    matchScore: "Identity Similarity",
    authenticityWarning: "WARNING: Identity verification measures vocal similarity. An AI-cloned voice can impersonate a target's voice print. Always cross-check the Synthetic Voice Risk rating.",
    disclaimerText: "DISCLAIMER: No AI deepfake detector is 100% infallible. VoiceShield output represents acoustic spectral probability and should be combined with multi-factor verification.",
    howItWorks: "Defense-In-Depth Security Analysis",
    step1: "Audio & Video Capture",
    step1Desc: "Upload WAV/MP3 files or MP4/WEBM videos or capture raw microphone and camera streams securely.",
    step2: "Acoustic & Vision Feature Extraction",
    step2Desc: "Extract 13-dimensional MFCCs, spectral centroid, zero-crossing rates, and YOLO object bounding boxes.",
    step3: "PyTorch & YOLO Inference",
    step3Desc: "Run features through PyTorch acoustic classifiers and YOLO26/YOLO11 object detection networks.",
    step4: "Explainable AI (Gemini)",
    step4Desc: "Feed numerical metrics to Gemini to generate standard plain-language cybersecurity evidence reports.",
    privacyNotice: "Privacy & Compliance Notice: VoiceShield adheres to SOC2 regulations. Scanned audio and video files are analyzed in-memory and immediately purged upon analysis.",
    howItWorksTitle: "How It Works",
    modelStatus: "Model Pipeline & Analytics Dashboard",
    modelName: "Model Name",
    status: "Status",
    auc: "Area Under ROC (AUC)",
    eer: "Equal Error Rate (EER)",
    dataset: "Training Dataset",
    lastUpdated: "Last Weights Update",
    modelDesc: "Overview of active neural networks, acoustic classifiers, and YOLO vision models running on this node."
  },
  hi: {
    title: "वॉयसशील्ड",
    tagline: "खतरे से पहले एआई वॉयस क्लोनिंग का पता लगाएं",
    taglineSub: "रीयल-टाइम डीपफेक ऑडियो विश्लेषण, योलो वीडियो मान्यता और सुरक्षा खुफिया जानकारी के साथ रक्षा करें।",
    landingCta1: "ऑडियो स्कैन शुरू करें",
    landingCta2: "योलो वीडियो स्कैन",
    landingCta3: "डैशबोर्ड देखें",
    navHome: "मुख्य",
    navDashboard: "डैशबोर्ड",
    navScan: "ऑडियो विश्लेषण",
    navYolo: "योलो वीडियो एआई",
    navLive: "लाइव ऑडियो",
    navVerify: "पहचान सत्यापन",
    navModels: "मॉडल हब",
    navArchitecture: "संरचना",
    language: "भाषा",
    totals: "कुल परीक्षित स्कैन",
    highRisk: "उच्च जोखिम अलर्ट",
    medRisk: "मध्यम जोखिम स्कैन",
    lowRisk: "कम जोखिम स्कैन",
    avgProb: "औसत कृत्रिम प्रोब",
    avgProc: "औसत विश्लेषण समय",
    historyTable: "घटना लॉग इतिहास",
    historyDesc: "ऑडियो और वीडियो स्कैन, जोखिम स्तर और साक्ष्य की विस्तृत सूची।",
    incidentId: "घटना आईडी",
    timestamp: "समय",
    fileName: "फ़ाइल का नाम",
    outcome: "स्कैन परिणाम",
    syntheticProb: "कृत्रिम संभावना",
    realProb: "वास्तविक संभावना",
    confidence: "आत्मविश्वास",
    riskLevel: "जोखिम स्तर",
    procTime: "प्रसंस्करण समय",
    actions: "कार्रवाई",
    viewReport: "रिपोर्ट देखें",
    downloadReport: "पीडीएफ डाउनलोड",
    deleteScan: "स्कैन हटाएं",
    modelPipeline: "मॉडल पाइपलाइन जानकारी",
    modelVersion: "मॉडल संस्करण",
    explainableAI: "एआई स्पष्टीकरण",
    securityChecklist: "सुरक्षा चेकलिस्ट",
    assistantTitle: "वॉयसशील्ड एआई सहायक",
    assistantPlaceholder: "स्कैन परिणाम, डीपफेक जोखिम के बारे में पूछें...",
    registerVoice: "संदर्भ आवाज दर्ज करें",
    registerDesc: "ध्वनिक पहचान स्थापित करने के लिए एक विश्वसनीय ऑडियो नमूना रिकॉर्ड या अपलोड करें।",
    compareVoice: "आने वाली आवाज सत्यापित करें",
    compareDesc: "समानता और क्लोनिंग जोखिम का मूल्यांकन करने के लिए एक पंजीकृत संदर्भ के साथ तुलना करें।",
    identityMatch: "आवाज पहचान मिलान",
    deepfakeRisk: "कृत्रिम आवाज जोखिम",
    matchScore: "समानता स्कोर",
    authenticityWarning: "चेतावनी: आवाज मिलान केवल समानता मापता है। एक एआई-क्लोन आवाज किसी की पहचान की नकल कर सकती है। हमेशा कृत्रिम आवाज जोखिम रेटिंग की जांच करें।",
    disclaimerText: "अस्वीकरण: कोई भी एआई डीपफेक डिटेक्टर 100% सटीक नहीं है। वॉयसशील्ड आउटपुट ध्वनिक संभावना का प्रतिनिधित्व करता है।",
    howItWorks: "गहन सुरक्षा विश्लेषण प्रक्रिया",
    step1: "ऑडियो और वीडियो कैप्चर",
    step1Desc: "WAV/MP3 ऑडियो या MP4 वीडियो फाइलें अपलोड करें।",
    step2: "विशेषता निष्कर्षण",
    step2Desc: "एमएफसीसी और योलो वस्तु पहचान सुविधाओं को निकालें।",
    step3: "पायटॉर्च और योलो अनुमान",
    step3Desc: "तंत्रिका नेटवर्क में चलाएं।",
    step4: "एआई स्पष्टीकरण (जेमिनी)",
    step4Desc: "जेमिनी की मदद से स्पष्ट भाषा में रिपोर्ट तैयार करें।",
    privacyNotice: "गोपनीयता सूचना: वॉयसशील्ड SOC2 नियमों का पालन करता है।",
    howItWorksTitle: "यह कैसे काम करता है",
    modelStatus: "मॉडल स्थिति और विश्लेषण",
    modelName: "मॉडल नाम",
    status: "स्थिति",
    auc: "AUC मेट्रिक",
    eer: "EER दर",
    dataset: "प्रशिक्षण डेटासेट",
    lastUpdated: "अंतिम अद्यतन",
    modelDesc: "सक्रिय तंत्रिका नेटवर्क का अवलोकन।"
  },
  kn: {
    title: "ವಾಯ್ಸ್‌ಶೀಲ್ಡ್",
    tagline: "ಕೃತಕ ಧ್ವನಿ ವಂಚನೆಯನ್ನು ಮೊದಲೇ ಪತ್ತೆಹಚ್ಚಿ",
    taglineSub: "ನೈಜ-ಸಮಯದ ಡೀಪ್‌ಫೇಕ್ ಆಡಿಯೊ ವಿಶ್ಲೇಷಣೆ, ಯೋಲೋ ವೀಡಿಯೊ ಗುರುತಿಸುವಿಕೆ ಮತ್ತು ಭದ್ರತಾ ಬುದ್ಧಿಮತ್ತೆಯೊಂದಿಗೆ ರಕ್ಷಿಸಿ.",
    landingCta1: "ಆಡಿಯೋ ಸ್ಕ್ಯಾನ್ ಪ್ರಾರಂಭಿಸಿ",
    landingCta2: "ಯೋಲೋ ವೀಡಿಯೊ ಸ್ಕ್ಯಾನ್",
    landingCta3: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ವೀಕ್ಷಿಸಿ",
    navHome: "ಮುಖಪುಟ",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navScan: "ಆಡಿಯೊ ವಿಶ್ಲೇಷಣೆ",
    navYolo: "ಯೋಲೋ ವೀಡಿಯೊ ಎಐ",
    navLive: "ಲೈವ್ ಆಡಿಯೊ",
    navVerify: "ಗುರುತು ಪರಿಶೀಲನೆ",
    navModels: "ಮಾದರಿ ಹಬ್",
    navArchitecture: "ರಚನೆ",
    language: "ಭಾಷೆ",
    totals: "ಒಟ್ಟು ಆಡಿಟ್ ಮಾಡಿದ ಸ್ಕ್ಯಾನ್‌ಗಳು",
    highRisk: "ಹೆಚ್ಚಿನ ಅಪಾಯದ ಅಲರ್ಟ್‌ಗಳು",
    medRisk: "ಮಧ್ಯಮ ಅಪಾಯದ ಸ್ಕ್ಯಾನ್‌ಗಳು",
    lowRisk: "ಕಡಿಮೆ ಅಪಾಯದ ಸ್ಕ್ಯಾನ್‌ಗಳು",
    avgProb: "ಸರಾಸರಿ ಕೃತಕ ಸಂಭವನೀಯತೆ",
    avgProc: "ಸರಾಸರಿ ವಿಶ್ಲೇಷಣಾ ಸಮಯ",
    historyTable: "ಘಟನೆ ಲಾಗ್ ಇತಿಹಾಸ",
    historyDesc: "ಆಡಿಯೊ ಮತ್ತು ವೀಡಿಯೊ ಸ್ಕ್ಯಾನ್‌ಗಳು, ಅಪಾಯದ ಮಟ್ಟಗಳು ಮತ್ತು ಸಾಕ್ಷ್ಯಗಳ ಪಟ್ಟಿ.",
    incidentId: "ಘಟನೆ ಐಡಿ",
    timestamp: "ಸಮಯ",
    fileName: "ಫೈಲ್ ಹೆಸರು",
    outcome: "ಸ್ಕ್ಯಾನ್ ಫಲಿತಾಂಶ",
    syntheticProb: "ಕೃತಕ ಧ್ವನಿ ಸಂಭವನೀಯತೆ",
    realProb: "ನೈಜ ಧ್ವನಿ ಸಂಭವನೀಯತೆ",
    confidence: "ವಿಶ್ವಾಸಾರ್ಹತೆ",
    riskLevel: "ಅಪಾಯದ ಮಟ್ಟ",
    procTime: "ಸಂಸ್ಕರಣಾ ಸಮಯ",
    actions: "ಕ್ರಮಗಳು",
    viewReport: "ವರದಿ ವೀಕ್ಷಿಸಿ",
    downloadReport: "ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್",
    deleteScan: "ಸ್ಕ್ಯಾನ್ ಅಳಿಸಿ",
    modelPipeline: "ಮಾದರಿ ಪೈಪ್‌ಲೈನ್ ಮಾಹಿತಿ",
    modelVersion: "ಮಾದರಿ ಆವೃತ್ತಿ",
    explainableAI: "ಎಐ ವಿವರಣೆ",
    securityChecklist: "ಸುರಕ್ಷತಾ ಪರಿಶೀಲನಾ ಪಟ್ಟಿ",
    assistantTitle: "ವಾಯ್ಸ್‌ಶೀಲ್ಡ್ ಎಐ ಸಹಾಯಕ",
    assistantPlaceholder: "ಸ್ಕ್ಯಾನ್ ಫಲಿತಾಂಶಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    registerVoice: "ಉಲ್ಲೇಖ ಧ್ವನಿ ನೋಂದಾಯಿಸಿ",
    registerDesc: "ಧ್ವನಿ ಗುರುತನ್ನು ಸ್ಥಾಪಿಸಲು ವಿಶ್ವಾಸಾರ್ಹ ಆಡಿಯೊ ಮಾದರಿಯನ್ನು ರೆಕಾರ್ಡ್ ಮಾಡಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    compareVoice: "ಬರುವ ಧ್ವನಿ ಪರಿಶೀಲಿಸಿ",
    compareDesc: "ಸಮಾನತೆ ಮತ್ತು ಕೃತಕ ಧ್ವನಿಯ ಅಪಾಯವನ್ನು ಮೌಲ್ಯಮಾಪನ ಮಾಡಲು ಹೋಲಿಕೆ ಮಾಡಿ.",
    identityMatch: "ಧ್ವನಿ ಗುರುತು ಹೊಂದಾಣಿಕೆ",
    deepfakeRisk: "ಕೃತಕ ಧ್ವನಿ ಅಪಾಯ",
    matchScore: "ಧ್ವನಿ ಹೋಲಿಕೆ ಸ್ಕೋರ್",
    authenticityWarning: "ಎಚ್ಚರಿಕೆ: ಗುರುತು ಪರಿಶೀಲನೆಯು ಧ್ವನಿಯ ಹೋಲಿಕೆಯನ್ನು ಅಳೆಯುತ್ತದೆ.",
    disclaimerText: "ಹಕ್ಕುತ್ಯಾಗ: ಯಾವುದೇ ಎಐ ಡೀಪ್‌ಫೇಕ್ ಡಿಟೆಕ್ಟರ್ 100% ಪರಿಪೂರ್ಣವಲ್ಲ.",
    howItWorks: "ವಾಯ್ಸ್‌ಶೀಲ್ಡ್ ಭದ್ರತಾ ವಿಶ್ಲೇಷಣೆ ಪ್ರಕ್ರಿಯೆ",
    step1: "ಆಡಿಯೋ ಮತ್ತು ವೀಡಿಯೊ ಸೆರೆಹಿಡಿಯುವಿಕೆ",
    step1Desc: "WAV/MP3 ಫೈಲ್‌ಗಳನ್ನು ಅಥವಾ MP4 ವೀಡಿಯೊಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    step2: "ವೈಶಿಷ್ಟ್ಯ ಹೊರತೆಗೆಯುವಿಕೆ",
    step2Desc: "ಎಂಎಫ್‌ಸಿಸಿ ಮತ್ತು ಯೋಲೋ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಹೊರತೆಗೆಯಿರಿ.",
    step3: "ಪೈಟಾರ್ಚ್ ತೀರ್ಮಾನ",
    step3Desc: "ತೀರ್ಮಾನ ತಂತ್ರಜ್ಞಾನಕ್ಕೆ ಕಳುಹಿಸಿ.",
    step4: "ಎಐ ವಿವರಣೆ (ಜೆಮಿನಿ)",
    step4Desc: "ವರದಿಗಳನ್ನು ರಚಿಸಿ.",
    privacyNotice: "ಗೌಪ್ಯತೆ ಸೂಚನೆ: ವಾಯ್ಸ್‌ಶೀಲ್ಡ್ SOC2 ನಿಯಮಗಳನ್ನು ಅನುಸರಿಸುತ್ತದೆ.",
    howItWorksTitle: "ಇದು ಹೇಗೆ ಕೆಲಸ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    modelStatus: "ಮಾದರಿ ಸ್ಥಿತಿ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ",
    modelName: "ಮಾದರಿ ಹೆಸರು",
    status: "ಸ್ಥಿತಿ",
    auc: "AUC ಮೆಟ್ರಿಕ್",
    eer: "EER ಪ್ರಮಾಣ",
    dataset: "ತರಬೇತಿ ಡೇಟಾಸೆಟ್",
    lastUpdated: "ಕೊನೆಯ ಅಪ್ಡೇಟ್",
    modelDesc: "ಸಕ್ರಿಯ ನರಮಂಡಲ ಜಾಲಗಳ ಅವಲೋಕನ."
  }
};
